name: AWS OIDC Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许你手动在网页上点击运行

permissions:
  id-token: write
  contents: read

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # 直接把 ARN 写死在这里测试，排除 Secret 没读到的可能性
          # 请把 "你的角色名称" 替换为真实的名字
          role-to-assume: arn:aws:iam::333076556197:role/TestOIDC-DebugRole
          aws-region: ap-northeast-1

      - name: Test AWS Identity
        run: aws sts get-caller-identity
